const Strings = {
  splashText: 'Simon Says',
  welcomePart1: 'Welcome to',
  welcomePart2: '"Simon Says"',
  instruction1: 'Watch the color sequence carefully!',
  instruction2: 'Repeat it by tapping to move forward.',
  currentScore: 'Your current score:',
  newGameButton: 'Start New Game',
  result_goTOGameScreen: 'I want to play',
  gameOver: 'Game Over',
  saveResultInstruction: 'Enter your name to save your score',
  fullNamePlaceholder: 'Full name',
  saveResultButton: 'Save Score',
  enterNameAlert: 'Please enter your name before saving the score',
  bestResultsTitle: 'Top 10 Scores',
  rankLabel: 'Rank',
  nameLabel: 'Name',
  scoreLabel: 'Score',
  screenResultsTitle: 'Best Results',
  screenHomeScreenTitle: 'Home Screen',
  screenGameScreensTitle: 'Simon Says Game',
  howToPlayVideo: 'How to Play (Video)',
  tutorialUrl: 'https://www.youtube.com/watch?v=vLi1qnRmpe4',
  noResultsText: 'No results yet. Play a game to see your top scores!',
  homeScreen_playBtn: 'Play a Game',
  homeScreen_viewResult: 'View Results',
};

export default Strings;
